# Generated by Django 5.0.6 on 2024-06-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=128)),
                ('tipo', models.IntegerField(choices=[(1, 'Professor'), (2, 'Aluno')])),
            ],
            options={
                'db_table': 'Minerva_Login',
                # 'managed': False,
            },
        ),
    ]
