# Generated by Django 5.0.6 on 2024-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_minerva_login_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usuario', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=255)),
                ('cargo', models.IntegerField()),
            ],
            options={
                'db_table': 'Minerva_Login',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Minerva_Login',
        ),
    ]
