# Generated by Django 4.2.13 on 2024-08-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minerva_Aluno',
            fields=[
                ('ra', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Minerva_Aluno',
            },
        ),
    ]
