# Generated by Django 4.2.13 on 2024-08-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minerva_aluno',
            options={'managed': False},
        ),
    ]
