# Generated by Django 4.2.13 on 2024-11-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_minerva_atividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minerva_Entrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='entregas/')),
                ('data_entrega', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Minerva_Entrega',
                'managed': False,
            },
        ),
    ]
