# Generated by Django 4.2.13 on 2024-08-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_alter_minerva_professor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.minerva_professor')),
            ],
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='professor.salaaula'),
        ),
        migrations.DeleteModel(
            name='SalaDeAula',
        ),
    ]
