# Generated by Django 4.2.13 on 2024-09-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_materia_salaaula_alter_mensagem_sala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataMatricula', models.DateField()),
            ],
            options={
                'db_table': 'Matricula_Turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorTurma_Teste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProfessorTurma_Teste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma_Teste',
            fields=[
                ('id_Turma', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTurma', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Turma_Teste',
                'managed': False,
            },
        ),
    ]
