# Generated by Django 4.2.13 on 2024-10-04 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_minerva_aluno_options'),
        ('professor', '0006_disciplina_teste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina_teste',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='MuralMensagem_Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.minerva_aluno')),
                ('id_Turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.turma_teste')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professor.minerva_professor')),
            ],
            options={
                'db_table': 'MuralMensagem_Teste',
                'managed': True,
            },
        ),
    ]
