# Generated by Django 4.2.13 on 2024-10-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_alter_disciplina_teste_options_muralmensagem_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
