# Generated by Django 4.2.13 on 2024-10-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_delete_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muralmensagem_teste',
            options={'managed': False},
        ),
    ]
