# Generated by Django 5.0.6 on 2024-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minerva_Login',
            fields=[
                ('usuario', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=128)),
                ('cargo', models.IntegerField(choices=[(1, 'Professor'), (2, 'Aluno')])),
            ],
            options={
                'db_table': 'Minerva_Login',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
