# Generated by Django 4.2.13 on 2024-08-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_minerva_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
