# Generated by Django 4.2.13 on 2024-08-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minerva_Professor',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('disciplina', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('dia_semana', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Minerva_Professor',
            },
        ),
    ]
